version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: aperture-tts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      retries: 20
    # I think we should be okay for ports because its in a single docker network since its one docker compose ? Unsure how docker works

  slack:
    image: ghcr.io/v3nco/aperture-tts-slack:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      database_url: ${DATABASE_URL}
    ports:
      - "8080:3000"
    volumes:
      - ./slack:/app
