[project]
name = "aperture-tts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "ipython>=9.7.0",
    "sentencepiece>=0.2.1",
    "style-bert-vits2>=2.5.0",
    "transformers>=4.57.1",
]
